name: Playwright Tests-new
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Workflow
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/rohithbb433/api-testing-playwright/actions/workflows/playwright.yml/dispatches \
          --data '{"ref":"main"}'

