name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Workflow
      run: gh workflow run -R rohithbb433/api-testing-playwright -f playwright.yml
      env:
        GH_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
