name: Trigger Another Workflow
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Trigger Another Workflow
        run: |
          const github = require('@actions/github');
          const token = process.env.TOKEN;
          const octokit = github.getOctokit(token);

          const triggerWorkflow = async () => {
            const { data } = await octokit.request('POST /repos/:owner/:repo/actions/workflows/:workflow_id/dispatches', {
              owner: 'rohithbb433,
              repo: 'api-testing-playwright',
              workflow_id: 'playwright.yml',
              ref: 'main',  // Specify the branch or tag you want to trigger the workflow on
              inputs: {
                customInput: 'value',
              },
            });

            console.log(data);
          };

          await triggerWorkflow();
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
